baseURL: "https://precious-praline-c0216f.netlify.app/"
languageCode: en-us
title: Leaf Guides
theme: PaperMod

params:
  homeInfoParams:
    Title: "Welcome to Leaf Guides"
    Content: "Here you will find lots of useful guides to installing all things for ~free"
  socialIcons:
    - name: github
      url: 'https://www.github.com/leafandJam'


  ShowbreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowShareButtons: false
  ShowToc: true

  defaultTheme: dark

outputs:
  home:
    - HTML
    - RSS
    - JSON


menu:
  main:
    - identifier: Categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: Archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: Search
      name: Search
      url: /search/
      weight: 10




