baseURL: "https://precious-praline-c0216f.netlify.app/"
languageCode: en-us
title: Leaf Guides
theme: PaperMod

params:
  homeInfoParams:
    Title: "Welcome to Leaf Guides"
    Content: "Here you will find lots of useful guides to installing all things for ~free"
  socialIcons:
    - name: github
      url: 'https://www.github.com/leafandJam'


  ShowbreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowShareButtons: false
  ShowToc: true
  ShowCodeCopyButtons: true
  hideFooter: false

  defaultTheme: dark

assets:
    favicon: "https://www.dropbox.com/s/k30gp7oqt4jd2jf/favicon.ico?dl=0"
    favicon16x16:  "https://previews.dropbox.com/p/thumb/ABgu25VObMiGJbY_RLr--7XZ1V4hyfBffTqFuvUUruI-I0X-lWc73_vvlbs06X7qtGbV_gUJeCYFv2FHkCdGzrR3COZROUkUd0y6OYFe-VSnIg3YwseJT2ajsYJDWRSCGZthYLuG9dRxufwuKsOFEAd9RJmbNCzgqrWMViDLrm9C5QwVVKjjtXvbMZfUsHWAa0A8ejOpOkeCe6wULHypl5XKMuZACx8F2JD1a74_2zXHrinQutCB9vPUlb7RP-Kg7Cy4dAfd7P4X3igFvEuXUoi0kIATP3YbR0SPUedAybJhTaIl9d2lUChQCboIjGw2lwoT41lCCsURGBO9o2d7HvZKEKe7rEB5UHddsNX9kwwmgh65iSRNEBSFqfKsuMwc9VM/p.png"
    favicon32x32:  "https://previews.dropbox.com/p/thumb/ABiRm2JymhHs0uSZ_1Z67DXI3jedkqWBBSD01iHW55JqPBsZEPYIWtSg3VqpsDk71-d8NsRn-ANl69MLDuH9gCClcAOjXiXvDletSDiDWEoM207RNzf5F6tyntLgUA6aYC8LxgPLlfvGv-VGUrtvDzG3_DNT3KuA_wlNEbdZgqw-oux18c2hMEr9CyKk4NfeILjCw3lqdFeOm6A7RFQGClTlVS6YvUN1ohiFklaths7cm7E-eNlKKEryEfs-JVXfAWMt5gj9NuPAfaM1odvb2HzL0JRHf3FuRE1U0KpGTHobBdSjJ-n_b8oT_PlwVJy16dxU_7ITR4P53ki2w4Xrs7NZkI8T4SfFJwnG9GfG64Hk8hteft0g6T4gs-P-Jgh0hyU/p.png"
    apple_touch_icon:  "https://previews.dropbox.com/p/thumb/ABgU37Korl0u1gIVHDa9SAZmm74Wg5HvnnVgfN45-joRBJQoVqNxILq_Ol_OtnUVluScFOP8hYfENm-jTU93zFuQkd0kmXTjqZymd-My_LXNaTjG8qnCCQntfniNJBumdMm8aBBL8_5MBmGyIpDedoCtQkULNvhQWFsuDAzIr7DHW3UwXcqZ2W_SF3_8AEwFTWB8reHCdhCEVvqa887UNwBIWbnoCdvncejhFJkBD71CGj-EPkT0gOYTxLZM-OsbkHHYtxsqthBBIKm_faz03gWuC87NO9fg9kbEiDMdDCxTgISH1goOeXdfYE-qf7lypfJuOYlSaxBgrsripQ90P54ZL-g3MPal6ND8_d8Izo6bHW5XKTtgbTf1TmcwpzLP5Q4/p.png"

outputs:
  home:
    - HTML
    - RSS
    - JSON


menu:
  main:
    - identifier: Categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: Archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: Search
      name: Search
      url: /search/
      weight: 10




