BaseURL: "https://leafguides.netlify.app/"
languageCode: en-us
title: Leaf.Guide
theme: PaperMod

params:
  homeInfoParams:
    Title: "Welcome to Leaf.Guide"
    Content: |
      Here you will find lots of useful guides to installing all things for ~free. 

      (Everything here is for educational purposes only.)  



      ~I have not updated these guides in a while, many are outdated.



  ShowbreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: false
  ShowShareButtons: false
  ShowToc: true
  ShowCodeCopyButtons: true
  hideFooter: false
  ShowCodeCopyButtons: true

  defaultTheme: dark


outputs:
  home:
    - HTML
    - RSS
    - JSON


menu:
  main:
    - identifier: Categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: Archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: Search
      name: Search
      url: /search/
      weight: 10




