BaseURL: "https://leaf-guides.vercel.app/"
languageCode: en-us
title: Leaf Guides
theme: PaperMod

params:
  homeInfoParams:
    Title: "Welcome to Leaf Guides" 
    Content: "Here you will find lots of useful guides to installing all things for ~free.
              (Everything here is strictly for educational purposes only. What you do with this information is up to you. Never pirate anything. Always pay for things!)"
    


  ignoreErrors: ["error-remote-getjson"]  #yml or ignoreErrors = ["error-remote-getjson"]  #toml 
  ShowbreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: false
  ShowShareButtons: false
  ShowToc: true
  ShowCodeCopyButtons: true
  hideFooter: false
  ShowCodeCopyButtons: true

  defaultTheme: dark


outputs:
  home:
    - HTML
    - RSS
    - JSON


menu:
  main:
    - identifier: Categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: Archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: Search
      name: Search
      url: /search/
      weight: 10




