BaseURL: "https://leaf.guides/"
languageCode: en-us
title: Leaf.Guide
theme: PaperMod

params:
  homeInfoParams:
    Title: "Welcome to Leaf.Guide"
    Content: >
      A collection of easy to follow guides I write. 
 
      (Everything here is for educational purposes only.)  





  ShowbreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: false
  ShowShareButtons: false
  ShowToc: true
  ShowCodeCopyButtons: true
  hideFooter: false
  ShowCodeCopyButtons: true

  defaultTheme: dark


outputs:
  home:
    - HTML
    - RSS
    - JSON


menu:
  main:
    - identifier: Categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: Archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: Search
      name: Search
      url: /search/
      weight: 10




